# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :bump_version_and_commit do
    # 获取当前版本号
    current_version = get_version_number

    # 自增版本号
    new_version = increment_build_number

    # 提交修改到源代码管理
    git_commit(
      path: '.',
      message: "Version bump to #{new_version}"
    )

  end
end
