# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
 
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :bump_version_and_commit do
    build_number = get_build_number#获取项目的build_number
    b = Integer(build_number)
    b = b + 1
    build_number = b.to_s
    #官方文档里并没有选择scheme的入参，所以当一个xcworkspace下有两个targets时，他们的build全部都会被更新。
    increment_build_number(
      build_number: build_number # set a specific number
    )
  end
end
