name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build + Publish
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set default Xcode version
      run: sudo xcode-select --switch /Applications/Xcode_14.2.app

    - name: Install Bundler
      run: gem install bundler

    - name: Install gems
      run: bundle install

    - name: Install pods
      run: bundle exec pod install

    - name: Build and upload
      run: bundle exec fastlane alpha
