name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build + Publish
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set default Xcode version
      run: sudo xcode-select --switch /Applications/Xcode_14.2.app

    - name: Install Bundler
      run: gem install bundler

    - name: Install gems
      run: bundle install

    - name: Install pods
      run: bundle exec fastlane bump_version_and_commit

    - name: Commit Changes
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add .
        git commit -m "Commit Message"
        git push

